#!/usr/bin/env python

from BaseHTTPServer import HTTPServer
from BaseHTTPServer import BaseHTTPRequestHandler
import cgi
import json

class RestHTTPRequestHandler(BaseHTTPRequestHandler):
  def do_GET(self):
    self.send_response(200)
    self.end_headers()
    self.wfile.write(json.dumps({'data': 'banana'}))
    return

httpd = HTTPServer(('0.0.0.0', 8000), RestHTTPRequestHandler)
while True:
    httpd.handle_request()

if __name__ == '__main__':
    main()